### ISSUE TITLE
is it possible to output how long it will take id words not numbers 

### ISSUE THREAD

**Issue by Zaku71** [Zaku71/Astronomy-Final-Project#5]
I want my code to output (__years__months__weeks__days__hours__) instead of just a number of days, months, or years, but I don't know how to start to go about this. I was thinking I could tell it to print said time interval from the defined time spans, but I don't know how to make it round to the whole integer and then use the remainder to find the next one.

any advice would be much appreciated!!

**Comment by nonlaminar** [comment]
Yes! This is very possible. Remember that we have number of days, so we can use some math to turn it into years months weeks days hours if we want. The part after the `#` is attempting to explain what it does. If this doesn't make sense feel free to leave more comments! 
Months is kind of hard, because every month has a different number of days so unless you really really want it, I would avoid using it. Typically computer timing things will do (Years, Weeks, Days, Hours (minutes seconds optional)) just to avoid months since they change depending on which month.

```
days = (some number)                              # This is the value you already have
years = days / 365                                    # this gets the number of years exactly! This will have a decimal, so you just want the int
leftover_days = days % 365                      # This is the modulus operator, it gets the remainder after dividing by the number after it
weeks = leftover_days / 7                         # Dividing the days by 7 to get number of weeks
new_leftover_days = leftover_days % 7   # you don't have to make a new variable here, but I did for readability
not_whole_days = days - int(days)           # Remember that int rounds down, so if we subtract the int part we get just the decimal
days = int(days)                                        # Will get only the whole number of days
hours = not_whole_days * 24                   # gets the hours from the decimal part of the days
```

**Comment by nonlaminar** [comment]
I just realized that you probably ment you wanted to change a value from displaying like a float (`3.6455`) to just (`3`). If you have a float value and you just want the integer part, you use a typecast! this is done by using the type as a function, and passing the value to it as an argument:

```
years = 3123.123     # This is a float value

years_int = int(years)   # this is now an int

print(years_int)
``` 
This code will print `3123` only, without the decimal part

**Comment by Zaku71** [comment]
I think the top one was what I wanted because I want to print out "it will take you 10 years 37 weeks and 5 days to get to Neptune" or something along those lines.

**Comment by Zaku71** [comment]
also do I need to add anything to make the decades and century's work or can I just put them above?

**Comment by nonlaminar** [comment]
Gotcha, yeah. Since they are all just variables, as long as you put them in the code in an order that makes sense it should work. Since some of the variables require that other variables have stuff in them, you need to put them in the right order. For-instance I cant calculate decades from days if I don't have days. 
For decades, If you have `years` you can just divide by 10 to get decades and store that to the `decades` variable.

**Comment by nonlaminar** [comment]
So to utilize the date function you can do as follows:
underneath line 61 `today = datetime.today()`
you can put
```
today_year = today.year
today_month = today.month
today_day = today.day
```

**Comment by nonlaminar** [comment]
When you are printing out the date:
you can use 

```arriaval_year = today_year + years```

**Comment by Zaku71** [comment]
works now
